name: deploy a node.js application on Azure app

on:
  push:
    branches: 
     - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: nodeapp-nandha    # application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'       # path to your web app project
  NODE_VERSION: '20.x'                 # node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
        
    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
